### ISSUE TITLE
Геолокация по IP

### ISSUE THREAD

**Issue by hkdobrev** [ti-broish/api#135]

**Comment by krokodilerian** [comment]
Бележка: геолокацията по ip при при мобилни мрежи не се справя по-добре от това да посочи държавата. За някакви wifi мрежи може да е по-добре, но пак за райони ще е сложно (и в София няма начин да различи 3-те МИР-а дори донякъде reliably). Хари спомена, че да питаме browser-а за location вероятно ще е алтернативния начин да се улесни човека да си подаде сигнала.

**Comment by hkdobrev** [comment]
Да, за съжаление @krokodilerian е прав и при мобилна мрежа няма да можем да засечем правилно града. Така че ще разчитаме на селектор на секция + евентуално ако човек разреши локацията в браузъра.
