### ISSUE TITLE
Текст за публикуване на сигнал

### ISSUE THREAD

**Issue by hkdobrev** [ti-broish/api#37]
Когато юрист иска да публикува сигнал трябва да му излиза textarea поле, което да е предварително попълнено с авторския текст от описанието на сигнала.

Юристът може да коригира текста или да редактира лични данни.

Това поле се записва и се показва в админа за публикувани сигнали редом до описанието с възможност за редакция.

В сайта публикуваните сигнали се показват само с този текст за публикуване, а не с оригиналния текст на сигналоподателя.

**Comment by jenikostadinova** [comment]
Дублира се с #37

**Comment by hkdobrev** [comment]
@jenikostadinova то това е #37 🤔

![image](https://user-images.githubusercontent.com/506129/122430075-f3acca00-cf9b-11eb-9430-ddd5574431bd.png)

**Comment by hkdobrev** [comment]
Имплементирано от #82
