### ISSUE TITLE
Преименуване на sendAPNToken API-то

### ISSUE THREAD

**Issue by photown** [ti-broish/api#68]
APN e Apple Push Notification, което е специфично за Apple. Понеже същото API се вика и от Android, е добре или да се преименува на нещо по-общо, например sendPushNotificationToken, или да се добави ново API, което да е специфично за Android, например sendFCMToken.

**Comment by hkdobrev** [comment]
@photown Къде точно има sendAPNToken в backend API-то?

**Comment by photown** [comment]
Сега проверих, оказа се че не ползваме такова АПИ, а ползваме `/me/clients`. `sendAPNToken` е било само локално име, а не име на АПИ. Затварям бъга.
